old_sound_rabbit_mq:
    connections:
        default:
            host: 'rabbitmq'
            port: 5672
            user: 'guest'
            password: 'guest'
            vhost: '/'
    producers:
        event_producer:
            connection: default
            exchange_options:
                name: 'events_exchange'
                type: 'direct'
